import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { validateLeadTimeBands, validateOccupancyBands } from "./priceRuleBands";
import type { BandDefect } from "./priceRuleBands";

// Reads tests/price_rules_band_conformance_fixtures.json — generated by
// tests/generate_price_rules_band_conformance_fixtures.py, which queries
// the REAL price_rules_is_valid_lead_time_bands / price_rules_is_valid_occupancy_bands
// SQL functions (db/migrations/0006_price_rules.sql) directly, not
// hand-typed here. Two independent guarantees, checked separately:
//
// 1. expectedValid comes from Postgres itself — the accept/reject
//    decision this test enforces is the one thing standing between "the
//    band editor looks right" and "the band editor agrees with the
//    database it's about to write to". If this drifts, an admin could
//    either be blocked from saving a config Postgres would accept, or —
//    worse — see no error client-side for a config Postgres will reject
//    with a raw check-constraint message.
// 2. expectedDefect is authored by hand in the generator, not derived
//    from Postgres (a CHECK constraint returns a boolean, never a
//    reason) — it is the fixture author's own judgment about which
//    problem each case is meant to exercise, checked here only against
//    priceRuleBands.ts's own classification. This catches a narrower but
//    real failure mode the boolean check alone would miss silently: two
//    cases can agree on "reject" while disagreeing on *why* — the editor
//    tells an admin "there's a gap" when the real problem is an overlap,
//    and a boolean-only conformance check would still pass.
interface FixtureCase {
  name: string;
  kind: "lead_time" | "occupancy";
  bands: unknown;
  valueKey: string;
  expectedValid: boolean;
  expectedDefect: BandDefect;
}

interface Fixtures {
  cases: FixtureCase[];
}

const FIXTURES_PATH = new URL(
  "../../tests/price_rules_band_conformance_fixtures.json",
  import.meta.url
);
const fixtures = JSON.parse(readFileSync(FIXTURES_PATH, "utf-8")) as Fixtures;

describe("priceRuleBands.ts matches the real Postgres band validators", () => {
  for (const testCase of fixtures.cases) {
    it(`${testCase.name}: valid=${testCase.expectedValid}, defect=${testCase.expectedDefect}`, () => {
      const result =
        testCase.kind === "lead_time"
          ? validateLeadTimeBands(testCase.bands, testCase.valueKey, "القيمة")
          : validateOccupancyBands(testCase.bands);

      expect(result.valid, "accept/reject decision must match Postgres").toBe(
        testCase.expectedValid
      );
      expect(
        result.defect,
        "defect classification must match this fixture's hand-authored expectation"
      ).toBe(testCase.expectedDefect);
    });
  }
});
