// TypeScript port of db/migrations/0006_price_rules.sql's
// price_rules_is_valid_lead_time_bands and price_rules_is_valid_occupancy_bands
// — the two SQL functions the price_rules CHECK constraints call. This port
// exists so a malformed band configuration is rejected in the admin form
// with an Arabic message naming the exact problem, before it ever reaches
// Postgres and surfaces as a raw "violates check constraint
// price_rules_min_profit_bands_valid" string (see admin/lib/postgresErrors.ts
// for the layer-2 fallback if one still gets through).
//
// The accept/reject decision (BandValidationResult.valid) is the part with
// a real cross-language source of truth — admin/lib/priceRuleBands.conformance.test.ts
// asserts it against tests/price_rules_band_conformance_fixtures.json,
// generated by querying the real SQL functions directly (not reasoned
// about by hand). The specific defect classification (BandValidationResult.defect)
// has no such source of truth: Postgres's CHECK constraint returns a bare
// boolean, never a reason, so that half of this module's output is
// TypeScript-only judgment, checked only against hand-authored expectations
// in the same fixture file. See that file's own comment for the split.

export type BandDefect =
  | "missing_key"
  | "wrong_type"
  | "negative_value"
  | "missing_zero_start"
  | "missing_open_end"
  | "gap"
  | "overlap"
  | "valid";

export interface BandValidationResult {
  valid: boolean;
  defect: BandDefect;
  // Arabic, names the offending band/values directly (e.g. the exact gap's
  // bounds) — never a generic "invalid" message. Empty string when valid.
  message: string;
}

interface ParsedBand {
  index: number;
  min: number;
  max: number | null;
  value: number;
}

const VALID: BandValidationResult = { valid: true, defect: "valid", message: "" };

function invalid(defect: BandDefect, message: string): BandValidationResult {
  return { valid: false, defect, message };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

// Structural pass shared by both validators: bands must be a non-empty
// array, and every element must carry minKey/valueKey as numbers and
// maxKey as either a number or (only when maxIsNullable) null. Mirrors the
// SQL functions' first two NOT EXISTS blocks, but — unlike SQL, which
// bundles "missing" and "wrong type" into one jsonb_typeof check — reports
// which of the two it actually was, since that distinction costs nothing
// in TypeScript and reads better to a non-technical admin.
function parseBands(
  raw: unknown,
  opts: { minKey: string; maxKey: string; valueKey: string; maxIsNullable: boolean }
): ParsedBand[] | BandValidationResult {
  if (!Array.isArray(raw) || raw.length === 0) {
    return invalid("missing_key", "لا توجد أي فترات معرّفة — يجب إضافة فترة واحدة على الأقل.");
  }

  const parsed: ParsedBand[] = [];
  for (const [index, rawBand] of raw.entries()) {
    const position = index + 1;
    if (!isPlainObject(rawBand)) {
      return invalid("wrong_type", `الفترة رقم ${position} ليست بالشكل الصحيح.`);
    }
    for (const key of [opts.minKey, opts.valueKey]) {
      if (!(key in rawBand)) {
        return invalid("missing_key", `الفترة رقم ${position} تفتقد الحقل "${key}".`);
      }
      if (typeof rawBand[key] !== "number") {
        return invalid("wrong_type", `الفترة رقم ${position}: الحقل "${key}" يجب أن يكون رقماً.`);
      }
    }
    if (!(opts.maxKey in rawBand)) {
      return invalid("missing_key", `الفترة رقم ${position} تفتقد الحقل "${opts.maxKey}".`);
    }
    const rawMax = rawBand[opts.maxKey];
    let max: number | null;
    if (rawMax === null) {
      if (!opts.maxIsNullable) {
        return invalid(
          "wrong_type",
          `الفترة رقم ${position}: الحقل "${opts.maxKey}" يجب أن يكون رقماً (لا مفتوحة).`
        );
      }
      max = null;
    } else if (typeof rawMax === "number") {
      max = rawMax;
    } else {
      return invalid(
        "wrong_type",
        `الفترة رقم ${position}: الحقل "${opts.maxKey}" يجب أن يكون رقماً${
          opts.maxIsNullable ? " أو فارغاً" : ""
        }.`
      );
    }
    parsed.push({
      index: position,
      min: rawBand[opts.minKey] as number,
      max,
      value: rawBand[opts.valueKey] as number,
    });
  }
  return parsed;
}

// Shared chain-shape check: every band's own values must be non-negative
// and internally consistent (max > min when max is a number), the chain
// must start at 0 and cover its domain with no gap or overlap between
// consecutive bands once sorted by min. domainEnd is null for an
// open-ended domain (lead time — exactly one band's max must be null) or
// a number for a closed domain (occupancy — the highest max must equal it
// exactly, and no band's max may exceed it).
function validateChain(
  bands: ParsedBand[],
  opts: { domainEnd: number | null; valueLabel: string }
): BandValidationResult {
  for (const band of bands) {
    if (band.min < 0) {
      return invalid(
        "negative_value",
        `الفترة رقم ${band.index}: بداية الفترة لا يمكن أن تكون سالبة.`
      );
    }
    if (band.value < 0) {
      return invalid(
        "negative_value",
        `الفترة رقم ${band.index}: ${opts.valueLabel} لا يمكن أن تكون سالبة.`
      );
    }
    if (opts.domainEnd !== null && band.max !== null && band.max > opts.domainEnd) {
      return invalid(
        "negative_value",
        `الفترة رقم ${band.index}: النهاية تتجاوز الحد الأقصى المسموح (${opts.domainEnd}).`
      );
    }
    if (band.max !== null && band.max <= band.min) {
      return invalid(
        "negative_value",
        `الفترة رقم ${band.index}: النهاية يجب أن تكون أكبر من البداية.`
      );
    }
  }

  const sorted = [...bands].sort((a, b) => a.min - b.min);

  if (sorted[0].min !== 0) {
    return invalid(
      "missing_zero_start",
      `الفترات يجب أن تبدأ من الصفر — أول فترة تبدأ من ${sorted[0].min}.`
    );
  }

  if (opts.domainEnd === null) {
    // Open-ended domain (lead time): exactly one band must be the
    // open-ended terminal band (max === null).
    const openEnded = sorted.filter((band) => band.max === null);
    if (openEnded.length === 0) {
      return invalid(
        "missing_open_end",
        "لا توجد فترة مفتوحة النهاية — يجب أن تغطي آخر فترة كل ما بعدها."
      );
    }
    if (openEnded.length > 1) {
      return invalid(
        "overlap",
        `أكثر من فترة مفتوحة النهاية في نفس الوقت (تبدأ من ${openEnded
          .map((b) => b.min)
          .join(" و")}).`
      );
    }
  } else {
    const highestMax = Math.max(...sorted.map((band) => band.max ?? -Infinity));
    if (highestMax !== opts.domainEnd) {
      return invalid(
        "missing_open_end",
        `الفترات لا تصل إلى الحد الأقصى (${opts.domainEnd}) — تنتهي عند ${highestMax}.`
      );
    }
  }

  for (let i = 0; i < sorted.length - 1; i++) {
    const current = sorted[i];
    const next = sorted[i + 1];
    if (current.max === null) {
      // The open-ended band, if present here, must be last after sorting
      // by min — a band starting after it would itself violate the
      // "exactly one open-ended band" rule above, so this is unreachable
      // in practice but guarded for completeness.
      continue;
    }
    if (current.max < next.min) {
      return invalid(
        "gap",
        `فجوة بين الفترتين: من ${current.max} إلى ${next.min} غير مغطّاة بأي فترة.`
      );
    }
    if (current.max > next.min) {
      return invalid(
        "overlap",
        `تداخل بين الفترتين: الفترة المنتهية عند ${current.max} تتداخل مع الفترة التي تبدأ من ${next.min}.`
      );
    }
  }

  return VALID;
}

// Mirrors price_rules_is_valid_lead_time_bands(bands jsonb, value_key text)
// — shared shape for min_profit_by_lead_time.bands (value_key
// "min_profit_halalas") and demand_curve.lead_time_bands (value_key
// "multiplier_bps"). valueLabel is the Arabic name shown in messages.
export function validateLeadTimeBands(
  raw: unknown,
  valueKey: string,
  valueLabel: string
): BandValidationResult {
  const parsed = parseBands(raw, {
    minKey: "min_lead_days",
    maxKey: "max_lead_days",
    valueKey,
    maxIsNullable: true,
  });
  if (!Array.isArray(parsed)) {
    return parsed;
  }
  return validateChain(parsed, { domainEnd: null, valueLabel });
}

// Mirrors price_rules_is_valid_occupancy_bands(bands jsonb) —
// demand_curve.occupancy_bands. Occupancy is closed 0..1, both ends
// inclusive, unlike lead time's open upper end — so max may never be
// null here, and the chain must reach exactly 1, not stay open forever.
export function validateOccupancyBands(raw: unknown): BandValidationResult {
  const parsed = parseBands(raw, {
    minKey: "min",
    maxKey: "max",
    valueKey: "multiplier_bps",
    maxIsNullable: false,
  });
  if (!Array.isArray(parsed)) {
    return parsed;
  }
  return validateChain(parsed, { domainEnd: 1, valueLabel: "المضاعِف" });
}
