import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { resolveYearCoverage } from "./seasonCalendar";
import type { Season } from "./types";

// Reads tests/season_conformance_fixtures.json — generated by
// tests/generate_season_conformance_fixtures.py from the REAL
// services/pricing/seasons.py (season_contains + resolve_season_id), not
// hand-typed here. This is the one thing standing between "the calendar
// preview looks right" and "the calendar preview agrees with the pricing
// engine": if either side's resolution logic changes without the other,
// this test fails — see the generator's module docstring for how to
// regenerate the fixture after a deliberate season_contains change.
interface FixtureSeason {
  id: number;
  season_name: string;
  calendar_type: Season["calendar_type"];
  start_month: number;
  start_day: number;
  end_month: number;
  end_day: number;
  priority: number;
  is_default: boolean;
}

interface FixtureDay {
  date: string;
  hijriYear: number;
  matching: string[];
  winner: string | null;
}

interface FixtureScenario {
  name: string;
  seasons: FixtureSeason[];
  days: FixtureDay[];
}

interface Fixtures {
  scenarios: FixtureScenario[];
}

const FIXTURES_PATH = new URL(
  "../../tests/season_conformance_fixtures.json",
  import.meta.url
);
const fixtures = JSON.parse(readFileSync(FIXTURES_PATH, "utf-8")) as Fixtures;

// created_at is part of the real Season type (mirrors the DB row) but
// nothing in seasonCalendar.ts's window-resolution logic reads it — the
// fixture doesn't carry it, so a placeholder satisfies the type without
// claiming a real value.
function toSeason(fixtureSeason: FixtureSeason): Season {
  return { ...fixtureSeason, created_at: "" };
}

describe("seasonCalendar.ts matches services/pricing/seasons.py", () => {
  for (const scenario of fixtures.scenarios) {
    describe(scenario.name, () => {
      const seasons = scenario.seasons.map(toSeason);
      const hijriYearsNeeded = [...new Set(scenario.days.map((day) => day.hijriYear))];

      for (const hijriYear of hijriYearsNeeded) {
        // Computed once per year, exactly like the real calendar preview
        // does when the admin picks a year — not once per fixture day.
        const coverage = resolveYearCoverage(seasons, hijriYear);
        const coverageByDate = new Map(
          coverage.map((day) => [day.date.toISOString().slice(0, 10), day])
        );

        for (const day of scenario.days.filter((d) => d.hijriYear === hijriYear)) {
          it(`${day.date} (${hijriYear}H)`, () => {
            const actual = coverageByDate.get(day.date);
            expect(actual, `no coverage computed for ${day.date}`).toBeDefined();
            expect(
              actual!.matching.map((season) => season.season_name).sort()
            ).toEqual(day.matching);
            expect(actual!.winner?.season_name ?? null).toBe(day.winner);
          });
        }
      }
    });
  }
});
