import hijriReference from "./hijriCalendarReference.json";
import type { CalendarType, Season } from "./types";

// Mirrors services/pricing/seasons.py's window-resolution functions
// (_clamp_to_month, _end_instance_date, _wraps_year, _season_instance) so
// the calendar preview shows the same boundaries the pricing engine will
// actually apply. The one thing this module never does is compute a Hijri
// date itself — every Hijri fact (a month's real length, the Gregorian
// date a Hijri month starts on) comes from hijriCalendarReference.json,
// generated by tests/generate_hijri_calendar_reference.py from lib/hijri.py.
// CLAUDE.md rule 6: Hijri conversion happens in exactly one module: this
// is not a second one, it only reads that module's precomputed output.

interface HijriMonthEntry {
  month: number;
  length: number;
  gregorianStart: string;
}

interface HijriReferenceTable {
  firstYear: number;
  lastSelectableYear: number;
  years: Record<string, HijriMonthEntry[]>;
}

const HIJRI_REFERENCE = hijriReference as HijriReferenceTable;

// No Hijri month ever exceeds 30 days — a structural fact about the
// calendar itself (see lib/hijri.py's own module docstring), not a
// computed value. Mirrors _month_absolute_max's hijri branch.
const HIJRI_MONTH_ABSOLUTE_MAX = 30;

export const HIJRI_FIRST_YEAR = HIJRI_REFERENCE.firstYear;
export const HIJRI_LAST_SELECTABLE_YEAR = HIJRI_REFERENCE.lastSelectableYear;

export class HijriYearOutOfRangeError extends Error {}

function hijriMonthEntry(year: number, month: number): HijriMonthEntry {
  const yearTable = HIJRI_REFERENCE.years[String(year)];
  if (!yearTable) {
    throw new HijriYearOutOfRangeError(
      `Hijri year ${year} is outside the generated reference table ` +
        `(${HIJRI_REFERENCE.firstYear}-${
          Object.keys(HIJRI_REFERENCE.years).length + HIJRI_REFERENCE.firstYear - 1
        }). Regenerate it with tests/generate_hijri_calendar_reference.py.`
    );
  }
  const entry = yearTable[month - 1];
  if (!entry) {
    throw new HijriYearOutOfRangeError(`Hijri month ${month} is not 1-12`);
  }
  return entry;
}

function hijriMonthLength(year: number, month: number): number {
  return hijriMonthEntry(year, month).length;
}

function hijriMonthGregorianStart(year: number, month: number): Date {
  return new Date(hijriMonthEntry(year, month).gregorianStart + "T00:00:00Z");
}

function addDaysUTC(date: Date, days: number): Date {
  const result = new Date(date);
  result.setUTCDate(result.getUTCDate() + days);
  return result;
}

// The Gregorian reference-year trick from _month_absolute_max: February's
// true max (29) only depends on the year for leap years, so a fixed
// reference leap year (2000) gives the right answer for every month.
function gregorianMonthLength(year: number, month: number): number {
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}

function monthAbsoluteMax(calendarType: CalendarType, month: number): number {
  if (calendarType === "hijri") {
    return HIJRI_MONTH_ABSOLUTE_MAX;
  }
  return gregorianMonthLength(2000, month);
}

// Correct for a season's START boundary (inclusive): clamps day down to
// the real last day of (year, month) if day exceeds it.
function clampToMonth(
  calendarType: CalendarType,
  year: number,
  month: number,
  day: number
): Date {
  if (calendarType === "hijri") {
    const clamped = Math.min(day, hijriMonthLength(year, month));
    return addDaysUTC(hijriMonthGregorianStart(year, month), clamped - 1);
  }
  const clamped = Math.min(day, gregorianMonthLength(year, month));
  return new Date(Date.UTC(year, month - 1, clamped));
}

function rollToNextMonth(year: number, month: number): [number, number] {
  return month === 12 ? [year + 1, 1] : [year, month + 1];
}

// Resolves a season's END boundary (exclusive). A day at or beyond the
// absolute maximum for that month is a "through the end of the month"
// sentinel — see services/pricing/seasons.py's _end_instance_date for why
// clamping (correct for START) would be wrong here.
function endInstanceDate(
  calendarType: CalendarType,
  year: number,
  month: number,
  day: number
): Date {
  if (day < monthAbsoluteMax(calendarType, month)) {
    return clampToMonth(calendarType, year, month, day);
  }
  const [nextYear, nextMonth] = rollToNextMonth(year, month);
  return clampToMonth(calendarType, nextYear, nextMonth, 1);
}

function wrapsYear(
  startMonth: number,
  startDay: number,
  endMonth: number,
  endDay: number
): boolean {
  return endMonth < startMonth || (endMonth === startMonth && endDay <= startDay);
}

// The concrete [start, end) window for the occurrence of `season` whose
// start falls in `anchorYear`, in the season's own calendar.
function seasonInstance(season: Season, anchorYear: number): { start: Date; end: Date } {
  const start = clampToMonth(
    season.calendar_type,
    anchorYear,
    season.start_month,
    season.start_day
  );
  const wraps = wrapsYear(
    season.start_month,
    season.start_day,
    season.end_month,
    season.end_day
  );
  const endYear = wraps ? anchorYear + 1 : anchorYear;
  const end = endInstanceDate(season.calendar_type, endYear, season.end_month, season.end_day);
  return { start, end };
}

// A day at or beyond this sentinel is "through the end of the month" for
// the given calendar/month — the value the "حتى نهاية الشهر" toggle writes
// as end_day. Exported for the season edit form.
export function endOfMonthSentinel(calendarType: CalendarType, month: number): number {
  return monthAbsoluteMax(calendarType, month);
}

export interface HijriYearSpan {
  start: Date;
  end: Date;
}

// The Gregorian span [start, end) of a full Hijri year — used both to
// bound the preview's day sweep and to pick candidate anchor years for
// every season, regardless of the season's own calendar.
export function hijriYearGregorianSpan(hijriYear: number): HijriYearSpan {
  return {
    start: hijriMonthGregorianStart(hijriYear, 1),
    end: hijriMonthGregorianStart(hijriYear + 1, 1),
  };
}

// The Gregorian [start, end) span of a single Hijri month — used to slice
// a full year's day-by-day coverage into the 12 month blocks the preview
// renders, without re-deriving month lengths from anything but the table.
export function hijriMonthGregorianSpan(hijriYear: number, month: number): HijriYearSpan {
  const [nextYear, nextMonth] = rollToNextMonth(hijriYear, month);
  return {
    start: hijriMonthGregorianStart(hijriYear, month),
    end: hijriMonthGregorianStart(nextYear, nextMonth),
  };
}

function toUTCDateOnly(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}

// Every non-default season's concrete instances that could plausibly
// overlap [span.start, span.end) — tries the season's own-calendar year
// one before, at, and one after the displayed Hijri year, the same margin
// resolve_season_id gets from checking two anchor years for a single date,
// widened by one since this resolves a whole year span instead of a point.
function candidateInstancesOverlapping(
  season: Season,
  span: HijriYearSpan,
  hijriDisplayYear: number
): { start: Date; end: Date }[] {
  const anchorYearsToTry: number[] = [];
  if (season.calendar_type === "hijri") {
    // The season's own calendar is Hijri, same as the displayed year —
    // reuse it directly rather than deriving a Hijri year from a Gregorian
    // date (which would require the Gregorian->Hijri conversion this
    // module must never do).
    anchorYearsToTry.push(hijriDisplayYear - 1, hijriDisplayYear, hijriDisplayYear + 1);
  } else {
    const startYear = span.start.getUTCFullYear();
    const endYear = span.end.getUTCFullYear();
    for (let year = startYear - 1; year <= endYear + 1; year += 1) {
      anchorYearsToTry.push(year);
    }
  }

  return anchorYearsToTry
    .map((anchorYear) => seasonInstance(season, anchorYear))
    .filter((instance) => instance.start < span.end && instance.end > span.start);
}

// Which generated Hijri year's Gregorian span contains `now` — a lookup
// against the precomputed table, not a Gregorian->Hijri conversion, so it
// stays inside this module's "read the table, never compute Hijri facts"
// rule. Used only to pick a sensible initial year for the preview's
// switcher; falls back to the nearest bound if `now` is outside the
// generated range (e.g. a stale reference table).
export function currentHijriYearEstimate(now: Date): number {
  for (let year = HIJRI_FIRST_YEAR; year <= HIJRI_LAST_SELECTABLE_YEAR; year += 1) {
    const span = hijriYearGregorianSpan(year);
    if (span.start <= now && now < span.end) {
      return year;
    }
  }
  const firstSpan = hijriYearGregorianSpan(HIJRI_FIRST_YEAR);
  return now < firstSpan.start ? HIJRI_FIRST_YEAR : HIJRI_LAST_SELECTABLE_YEAR;
}

export interface DayCoverage {
  date: Date;
  /** Highest-priority matching non-default season, or null (falls back to
   * the default season, same as resolve_season_id). */
  winner: Season | null;
  /** Every non-default season whose window contains this day, winner
   * included — length > 1 means a contested/overlapping day. */
  matching: Season[];
}

// Mirrors resolve_season_id's per-day decision (highest priority wins,
// ties break toward the lower id / earlier created), applied to every day
// in a Hijri year's Gregorian span, plus the raw set of every matching
// season so the UI can render contested days distinctly (hatched).
export function resolveYearCoverage(seasons: Season[], hijriDisplayYear: number): DayCoverage[] {
  const span = hijriYearGregorianSpan(hijriDisplayYear);
  const nonDefault = seasons.filter((season) => !season.is_default);

  const instancesBySeasonId = new Map<number, { start: Date; end: Date }[]>();
  for (const season of nonDefault) {
    instancesBySeasonId.set(
      season.id,
      candidateInstancesOverlapping(season, span, hijriDisplayYear)
    );
  }

  const days: DayCoverage[] = [];
  for (let cursor = toUTCDateOnly(span.start); cursor < span.end; cursor = addDaysUTC(cursor, 1)) {
    const matching = nonDefault.filter((season) =>
      (instancesBySeasonId.get(season.id) ?? []).some(
        (instance) => instance.start <= cursor && cursor < instance.end
      )
    );
    const winner =
      matching.length === 0
        ? null
        : matching.reduce((best, candidate) =>
            candidate.priority > best.priority ||
            (candidate.priority === best.priority && candidate.id < best.id)
              ? candidate
              : best
          );
    days.push({ date: new Date(cursor), winner, matching });
  }
  return days;
}
